import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseAnonKey ? createClient(supabaseUrl, supabaseAnonKey) : null;
const SHARED_OPERATOR_EMAIL = 'aravindhan090804@gmail.com';
const MACHINES = Array.from({ length: 17 }, (_, i) => ({ id: i + 1, machine_no: `M-${String(i + 1).padStart(2, '0')}` }));

function localDate() { const now = new Date(); const offset = now.getTimezoneOffset(); return new Date(now.getTime() - offset * 60000).toISOString().slice(0, 10); }

function Login({ onLogin }) {
  const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(e) { e.preventDefault(); setError(''); if (!supabase) return setError('The app is not configured correctly.'); if (!password) return setError('Please enter the access password.'); setLoading(true); const { data, error } = await supabase.auth.signInWithPassword({ email: SHARED_OPERATOR_EMAIL, password }); setLoading(false); if (error) return setError('Incorrect access password. Please try again.'); onLogin(data.session); }
  return <main className="page-center"><section className="card login-card"><div className="brand">SHAMPOO PLANT</div><h1>Plant Access</h1><p className="muted">Enter the shared access password to continue.</p><form onSubmit={submit}><label htmlFor="access-password">Access password</label><input id="access-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password" autoFocus />{error&&<div className="error">{error}</div>}<button type="submit" disabled={loading}>{loading?'Checking…':'ENTER'}</button></form></section></main>;
}

function ProductionEntry({ session, onSaved }) {
  const [form,setForm]=useState({date:localDate(),shift:'Shift 1',timing:'',machine:'M-01',operator:'',collectionOperator:'',laminateSupplier:'',defect:'',qc:'',totalCld:'',acceptedCld:'',rejectedCld:''});
  const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const update=(key,value)=>{setMessage('');setError('');setForm(f=>({...f,[key]:value}));};
  async function save(e){e.preventDefault();setMessage('');setError();const required=['date','shift','machine','operator','defect','totalCld','acceptedCld','rejectedCld'];if(required.some(k=>!String(form[k]).trim()))return setError('Please fill all required fields before saving.');const total=Number(form.totalCld),accepted=Number(form.acceptedCld),rejected=Number(form.rejectedCld),defect=Number(form.defect);if([total,accepted,rejected,defect].some(v=>!Number.isFinite(v)||v<0))return setError('CLD and Defect values must be zero or greater.');if(accepted+rejected!==total)return setError('Accepted CLD + Rejected CLD must equal Total CLD.');if(!supabase)return setError('Supabase is not configured.');setSaving(true);const {data:machine,error:machineError}=await supabase.from('machines').select('id').eq('machine_no',form.machine).single();if(machineError||!machine){setSaving(false);return setError('Could not find the selected machine.');}const {error:insertError}=await supabase.from('production_records').insert({production_date:form.date,shift:form.shift,timing:form.timing||null,machine_id:machine.id,operator_name:form.operator,collection_operator_name:form.collectionOperator||null,laminate_supplier_name:form.laminateSupplier||null,defect,qc:form.qc||null,clds_total:total,accepted_cld:accepted,rejected_cld:rejected,created_by:session?.user?.id||null,updated_by:session?.user?.id||null});setSaving(false);if(insertError)return setError(`Could not save the entry: ${insertError.message}`);setMessage('Production entry saved successfully.');onSaved?.();setForm(f=>({...f,timing:'',operator:'',collectionOperator:'',laminateSupplier:'',defect:'',qc:'',totalCld:'',acceptedCld:'',rejectedCld:''}));}
  return <><div className="page-heading"><div><h2>PRODUCTION ENTRY</h2><p>Enter the production details for the selected shift and machine.</p></div><div className="entry-date-badge">{form.date}</div></div><form className="production-form panel" onSubmit={save}><div className="form-grid"><div className="field"><label>Date</label><input type="date" value={form.date} onChange={e=>update('date',e.target.value)}/></div><div className="field"><label>Shift</label><select value={form.shift} onChange={e=>update('shift',e.target.value)}><option>Shift 1</option><option>Shift 2</option><option>Shift 3</option></select></div><div className="field"><label>Timing</label><input value={form.timing} onChange={e=>update('timing',e.target.value)}/></div><div className="field"><label>Machine</label><select value={form.machine} onChange={e=>update('machine',e.target.value)}>{MACHINES.map(m=><option key={m.id}>{m.machine_no}</option>)}</select></div><div className="field"><label>Operator</label><input value={form.operator} onChange={e=>update('operator',e.target.value)}/></div><div className="field"><label>Collection Operator</label><input value={form.collectionOperator} onChange={e=>update('collectionOperator',e.target.value)}/></div><div className="field field-wide"><label>Laminate Supplier</label><input value={form.laminateSupplier} onChange={e=>update('laminateSupplier',e.target.value)}/></div><div className="field"><label>Defect</label><input type="number" min="0" value={form.defect} onChange={e=>update('defect',e.target.value)}/></div><div className="field"><label>QC</label><input value={form.qc} onChange={e=>update('qc',e.target.value)}/></div><div className="field"><label>Total CLD</label><input type="number" min="0" value={form.totalCld} onChange={e=>update('totalCld',e.target.value)}/></div><div className="field"><label>Accepted CLD</label><input type="number" min="0" value={form.acceptedCld} onChange={e=>update('acceptedCld',e.target.value)}/></div><div className="field"><label>Rejected CLD</label><input type="number" min="0" value={form.rejectedCld} onChange={e=>update('rejectedCld',e.target.value)}/></div></div><div className="form-footer">{error&&<span className="error-inline">{error}</span>}{message&&<span className="save-message">{message}</span>}<button className="save-button" type="submit" disabled={saving}>{saving?'SAVING…':'SAVE'}</button></div></form></>;
}

function useProductionRecords(refreshKey){
  const [records,setRecords]=useState([]);const [machines,setMachines]=useState(MACHINES);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  useEffect(()=>{let active=true;async function load(){if(!supabase){setError('Supabase is not configured.');setLoading(false);return;}setLoading(true);setError('');const [r,m]=await Promise.all([supabase.from('production_records').select('id,machine_id,production_date,shift,timing,operator_name,collection_operator_name,laminate_supplier_name,defect,qc,clds_total,accepted_cld,rejected_cld').order('production_date',{ascending:false}).order('id',{ascending:false}),supabase.from('machines').select('id,machine_no').order('id',{ascending:true})]);if(!active)return;if(r.error)setError(r.error.message);else setRecords(r.data||[]);if(!m.error&&m.data?.length)setMachines(m.data);setLoading(false);}load();return()=>{active=false};},[refreshKey]);return{records,machines,loading,error};
}

function Filters({records,machines,date,setDate,shift,setShift,machine,setMachine}){const dates=[...new Set(records.map(r=>r.production_date).filter(Boolean))].sort().reverse();return <div className="dashboard-filters"><label>Date<select value={date} onChange={e=>setDate(e.target.value)}><option value="all">All dates</option>{dates.map(d=><option key={d}>{d}</option>)}</select></label><label>Shift<select value={shift} onChange={e=>setShift(e.target.value)}><option value="all">All shifts</option><option>Shift 1</option><option>Shift 2</option><option>Shift 3</option></select></label>{setMachine&&<label>Machine<select value={machine} onChange={e=>setMachine(e.target.value)}><option value="all">All machines</option>{machines.map(m=><option key={m.id} value={m.id}>{m.machine_no}</option>)}</select></label>}</div>}

function MachineDashboard({refreshKey}){const {records,machines,loading,error}=useProductionRecords(refreshKey);const [date,setDate]=useState('all');const [shift,setShift]=useState('all');const filtered=useMemo(()=>records.filter(r=>(date==='all'||r.production_date===date)&&(shift==='all'||r.shift===shift)),[records,date,shift]);const cumulative=useMemo(()=>filtered.reduce((s,r)=>({total:s.total+Number(r.clds_total||0),accepted:s.accepted+Number(r.accepted_cld||0),rejected:s.rejected+Number(r.rejected_cld||0),defect:s.defect+Number(r.defect||0)}),{total:0,accepted:0,rejected:0,defect:0}),[filtered]);const rows=machines.map(m=>{const rs=filtered.filter(r=>r.machine_id===m.id);return{...m,total:rs.reduce((s,r)=>s+Number(r.clds_total||0),0),accepted:rs.reduce((s,r)=>s+Number(r.accepted_cld||0),0),rejected:rs.reduce((s,r)=>s+Number(r.rejected_cld||0),0),defect:rs.reduce((s,r)=>s+Number(r.defect||0),0),qc:rs.length?rs[0].qc||'—':'—'};});return <><div className="page-heading"><div><h2>MACHINE OVERVIEW</h2><p>Overall cumulative and machine-wise production.</p></div><Filters records={records} machines={machines} date={date} setDate={setDate} shift={shift} setShift={setShift}/></div><div className="summary-grid"><div className="summary-card"><span>Total CLDs</span><strong>{cumulative.total}</strong></div><div className="summary-card"><span>Accepted CLD</span><strong>{cumulative.accepted}</strong></div><div className="summary-card"><span>Rejected CLD</span><strong>{cumulative.rejected}</strong></div><div className="summary-card"><span>Defect</span><strong>{cumulative.defect}</strong></div></div><div className="panel machine-panel"><div className="section-title"><h3>MACHINE-WISE RECORD</h3><p>All {machines.length} machines for the selected period.</p></div>{error&&<div className="error">Could not load dashboard: {error}</div>}{loading?<div className="dashboard-loading">Loading machine data…</div>:<div className="machine-table-wrap"><table className="machine-table"><thead><tr><th>Machine</th><th>Total CLD</th><th>Accepted CLD</th><th>Rejected CLD</th><th>Defect</th><th>QC</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.machine_no}</strong></td><td>{r.total}</td><td>{r.accepted}</td><td>{r.rejected}</td><td>{r.defect}</td><td>{r.qc}</td></tr>)}</tbody></table></div>}</div></>}

function ProductionHistory({refreshKey}){const {records,machines,loading,error}=useProductionRecords(refreshKey);const [date,setDate]=useState('all');const [shift,setShift]=useState('all');const [machine,setMachine]=useState('all');const machineMap=useMemo(()=>Object.fromEntries(machines.map(m=>[m.id,m.machine_no])),[machines]);const filtered=useMemo(()=>records.filter(r=>(date==='all'||r.production_date===date)&&(shift==='all'||r.shift===shift)&&(machine==='all'||String(r.machine_id)===String(machine))),[records,date,shift,machine]);return <><div className="page-heading"><div><h2>PRODUCTION HISTORY</h2><p>Complete production records, separately from the machine summary.</p></div><Filters records={records} machines={machines} date={date} setDate={setDate} shift={shift} setShift={setShift} machine={machine} setMachine={setMachine}/></div><div className="panel machine-panel"><div className="section-title"><h3>ALL PRODUCTION RECORDS</h3><p>{filtered.length} record{filtered.length===1?'':'s'} shown for the selected filters.</p></div>{error&&<div className="error">Could not load production history: {error}</div>}{loading?<div className="dashboard-loading">Loading production history…</div>:filtered.length===0?<div className="dashboard-loading">No production records match the selected filters.</div>:<div className="machine-table-wrap"><table className="machine-table history-table"><thead><tr><th>Date</th><th>Shift</th><th>Timing</th><th>Machine</th><th>Operator</th><th>Collection Operator</th><th>Laminate Supplier</th><th>Defect</th><th>QC</th><th>Total CLD</th><th>Accepted CLD</th><th>Rejected CLD</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td>{r.production_date}</td><td>{r.shift}</td><td>{r.timing||'—'}</td><td><strong>{machineMap[r.machine_id]||`M-${String(r.machine_id).padStart(2,'0')}`}</strong></td><td>{r.operator_name||'—'}</td><td>{r.collection_operator_name||'—'}</td><td>{r.laminate_supplier_name||'—'}</td><td>{r.defect??'—'}</td><td>{r.qc||'—'}</td><td>{r.clds_total??0}</td><td>{r.accepted_cld??0}</td><td>{r.rejected_cld??0}</td></tr>)}</tbody></table></div>}</div></>}

function App(){const [session,setSession]=useState(null);const [checking,setChecking]=useState(true);const [page,setPage]=useState('dashboard');const [refreshKey,setRefreshKey]=useState(0);useEffect(()=>{if(!supabase){setChecking(false);return;}supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe();},[]);if(checking)return <div className="loading">Loading…</div>;if(!session)return <Login onLogin={setSession}/>;const nav=[['dashboard','▦','Dashboard'],['entry','＋','Production Entry'],['history','☷','Production History']];return <div className="dashboard-shell"><aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark">SP</div><div><strong>SHAMPOO PLANT</strong><span>Production Control</span></div></div><nav>{nav.map(([id,icon,label])=><button key={id} className={`nav-item ${page===id?'active':''}`} onClick={()=>setPage(id)}><span className="nav-icon">{icon}</span>{label}</button>)}</nav><div className="sidebar-bottom"><div className="plant-state"><span className="status-dot"/><div><strong>System online</strong><span>Production database connected</span></div></div><button className="logout-button" onClick={()=>supabase?.auth.signOut()}>Log out</button></div></aside><main className="dashboard-main"><header className="topbar"><div><p className="eyebrow">PRODUCTION CONTROL</p><h1>{page==='dashboard'?'Machine Dashboard':page==='entry'?'Production Entry':'Production History'}</h1></div><div className="topbar-right"><span className="live-pill"><span className="status-dot"/>LIVE</span><span className="operator">Operator</span><span className="avatar">OP</span></div></header><section className="content">{page==='dashboard'?<MachineDashboard refreshKey={refreshKey}/>:page==='entry'?<ProductionEntry session={session} onSaved={()=>setRefreshKey(k=>k+1)}/>:<ProductionHistory refreshKey={refreshKey}/>}</section></main></div>}

createRoot(document.getElementById('root')).render(<App />);
