import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseAnonKey ? createClient(supabaseUrl, supabaseAnonKey) : null;
const SHARED_OPERATOR_EMAIL = 'aravindhan090804@gmail.com';
const MACHINES = Array.from({ length: 17 }, (_, i) => ({ id: i + 1, machine_no: `M-${String(i + 1).padStart(2, '0')}` }));

function Login({ onLogin }) {
  const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function handleSubmit(event) { event.preventDefault(); setError(''); if (!supabase) return setError('The app is not configured correctly. Please contact the supervisor.'); if (!password) return setError('Please enter the access password.'); setLoading(true); const { data, error: signInError } = await supabase.auth.signInWithPassword({ email: SHARED_OPERATOR_EMAIL, password }); setLoading(false); if (signInError) return setError('Incorrect access password. Please try again.'); onLogin(data.session); }
  return <main className="page-center"><section className="card login-card"><div className="brand">SHAMPOO PLANT</div><h1>Plant Access</h1><p className="muted">Enter the shared access password to continue.</p><form onSubmit={handleSubmit} noValidate><label htmlFor="access-password">Access password</label><input id="access-password" type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter password" autoFocus />{error && <div className="error" role="alert">{error}</div>}<button type="submit" disabled={loading}>{loading ? 'Checking…' : 'ENTER'}</button></form></section></main>;
}

function ProductionEntry({ session, onSaved }) {
  const [form, setForm] = useState({ date: '2026-09-19', shift: 'Shift 1', timing: '', machine: 'M-01', operator: '', collectionOperator: '', laminateSupplier: '', defect: '', qc: '', totalCld: '', acceptedCld: '', rejectedCld: '' });
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const update = (field, value) => { setMessage(''); setError(''); setForm(current => ({ ...current, [field]: value })); };
  async function saveEntry(event) { event.preventDefault(); setMessage(''); setError(''); const required = ['date','shift','machine','operator','defect','totalCld','acceptedCld','rejectedCld']; if (required.some(k => !String(form[k]).trim())) return setError('Please fill all required fields before saving.'); const total = Number(form.totalCld), accepted = Number(form.acceptedCld), rejected = Number(form.rejectedCld), defect = Number(form.defect); if ([total, accepted, rejected, defect].some(n => !Number.isFinite(n) || n < 0)) return setError('CLD and Defect values must be zero or greater.'); if (accepted + rejected !== total) return setError('Accepted CLD + Rejected CLD must equal Total CLD.'); setSaving(true); const machine = MACHINES.find(m => m.machine_no === form.machine); const { data: machineRow, error: machineError } = await supabase.from('machines').select('id').eq('machine_no', form.machine).single(); if (machineError || !machineRow) { setSaving(false); return setError('Could not find the selected machine.'); } const { error: insertError } = await supabase.from('production_records').insert({ production_date: form.date, shift: form.shift, timing: form.timing || null, machine_id: machineRow.id, operator_name: form.operator, collection_operator_name: form.collectionOperator || null, laminate_supplier_name: form.laminateSupplier || null, defect, qc: form.qc || null, clds_total: total, accepted_cld: accepted, rejected_cld: rejected, created_by: session?.user?.id || null, updated_by: session?.user?.id || null }); setSaving(false); if (insertError) return setError(`Could not save the entry: ${insertError.message}`); setMessage('Production entry saved successfully.'); onSaved?.(); setForm(current => ({ ...current, timing: '', operator: '', collectionOperator: '', laminateSupplier: '', defect: '', qc: '', totalCld: '', acceptedCld: '', rejectedCld: '' })); }
  return <><div className="page-heading"><div><h2>PRODUCTION ENTRY</h2><p>Enter the production details for the selected shift and machine.</p></div><div className="entry-date-badge">19/09/2026</div></div><form className="production-form panel" onSubmit={saveEntry}><div className="form-grid"><div className="field"><label>Date</label><input type="date" value={form.date} onChange={e => update('date', e.target.value)} /></div><div className="field"><label>Shift</label><select value={form.shift} onChange={e => update('shift', e.target.value)}><option>Shift 1</option><option>Shift 2</option><option>Shift 3</option></select></div><div className="field"><label>Timing</label><input value={form.timing} onChange={e => update('timing', e.target.value)} /></div><div className="field"><label>Machine</label><select value={form.machine} onChange={e => update('machine', e.target.value)}>{MACHINES.map(m => <option key={m.machine_no}>{m.machine_no}</option>)}</select></div><div className="field"><label>Operator</label><input value={form.operator} onChange={e => update('operator', e.target.value)} /></div><div className="field"><label>Collection Operator</label><input value={form.collectionOperator} onChange={e => update('collectionOperator', e.target.value)} /></div><div className="field field-wide"><label>Laminate Supplier</label><input value={form.laminateSupplier} onChange={e => update('laminateSupplier', e.target.value)} /></div><div className="field"><label>Defect</label><input type="number" min="0" value={form.defect} onChange={e => update('defect', e.target.value)} /></div><div className="field"><label>QC</label><input value={form.qc} onChange={e => update('qc', e.target.value)} /></div><div className="field"><label>Total CLD</label><input type="number" min="0" value={form.totalCld} onChange={e => update('totalCld', e.target.value)} /></div><div className="field"><label>Accepted CLD</label><input type="number" min="0" value={form.acceptedCld} onChange={e => update('acceptedCld', e.target.value)} /></div><div className="field"><label>Rejected CLD</label><input type="number" min="0" value={form.rejectedCld} onChange={e => update('rejectedCld', e.target.value)} /></div></div><div className="form-footer">{error && <span className="error-inline">{error}</span>}{message && <span className="save-message">{message}</span>}<button className="save-button" type="submit" disabled={saving}>{saving ? 'SAVING…' : 'SAVE'}</button></div></form></>;
}

function MachineDashboard({ refreshKey }) {
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [dateFilter, setDateFilter] = useState('all'); const [shiftFilter, setShiftFilter] = useState('all');
  useEffect(() => { let active = true; async function load() { setLoading(true); setError(''); const { data, error: queryError } = await supabase.from('production_records').select('machine_id, production_date, shift, clds_total, accepted_cld, rejected_cld, defect, qc').order('production_date', { ascending: false }); if (!active) return; if (queryError) setError(queryError.message); else setRecords(data || []); setLoading(false); } load(); return () => { active = false; }; }, [refreshKey]);
  const dates = useMemo(() => [...new Set(records.map(r => r.production_date).filter(Boolean))].sort().reverse(), [records]);
  const filteredRecords = useMemo(() => records.filter(r => (dateFilter === 'all' || r.production_date === dateFilter) && (shiftFilter === 'all' || r.shift === shiftFilter)), [records, dateFilter, shiftFilter]);
  const rows = useMemo(() => MACHINES.map(machine => { const rs = filteredRecords.filter(r => r.machine_id === machine.id); return { ...machine, total: rs.reduce((s,r) => s + Number(r.clds_total || 0),0), accepted: rs.reduce((s,r) => s + Number(r.accepted_cld || 0),0), rejected: rs.reduce((s,r) => s + Number(r.rejected_cld || 0),0), defect: rs.reduce((s,r) => s + Number(r.defect || 0),0), qc: rs.length ? [...rs].sort((a,b) => String(b.production_date).localeCompare(String(a.production_date)))[0].qc || '—' : '—' }; }), [filteredRecords]);
  const periodLabel = dateFilter === 'all' ? 'All dates' : dateFilter; const shiftLabel = shiftFilter === 'all' ? 'All shifts' : shiftFilter;
  return <><div className="page-heading"><div><h2>MACHINE OVERVIEW</h2><p>{periodLabel} · {shiftLabel} · cumulative totals from saved production records.</p></div><div className="dashboard-filters"><label>Date<select value={dateFilter} onChange={e => setDateFilter(e.target.value)}><option value="all">All dates</option>{dates.map(d => <option key={d} value={d}>{d}</option>)}</select></label><label>Shift<select value={shiftFilter} onChange={e => setShiftFilter(e.target.value)}><option value="all">All shifts</option><option>Shift 1</option><option>Shift 2</option><option>Shift 3</option></select></label></div></div><div className="panel machine-panel">{error && <div className="error">Could not load dashboard: {error}</div>}{loading ? <div className="dashboard-loading">Loading machine data…</div> : <div className="machine-table-wrap"><table className="machine-table"><thead><tr><th>Machine</th><th>Total CLD</th><th>Accepted CLD</th><th>Rejected CLD</th><th>Defect</th><th>QC</th></tr></thead><tbody>{rows.map(row => <tr key={row.machine_no}><td><strong>{row.machine_no}</strong></td><td>{row.total}</td><td>{row.accepted}</td><td>{row.rejected}</td><td>{row.defect}</td><td>{row.qc}</td></tr>)}</tbody></table></div>}</div></>;
}

function Dashboard({ onLogout, session }) { const [activeNav, setActiveNav] = useState('Machine Overview'); const [refreshKey, setRefreshKey] = useState(0); const navItems = ['Machine Overview', 'Production Entry', 'Production Records', 'Quality', 'Reports']; return <div className="dashboard-shell"><aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark">SP</div><div><strong>SHAMPOO PLANT</strong><span>Operations</span></div></div><nav>{navItems.map(item => <button key={item} className={`nav-item ${activeNav === item ? 'active' : ''}`} onClick={() => setActiveNav(item)}><span className="nav-icon">{item === 'Production Entry' ? '＋' : item === 'Machine Overview' ? '▦' : item === 'Quality' ? '✓' : item === 'Production Records' ? '▤' : '▧'}</span>{item}</button>)}</nav><div className="sidebar-bottom"><div className="plant-state"><span className="status-dot"/><div><strong>Plant online</strong><span>Production system ready</span></div></div><button className="logout-button" onClick={onLogout}>Log out</button></div></aside><main className="dashboard-main"><header className="topbar"><div><p className="eyebrow">SHAMPOO PLANT / OPERATIONS</p><h1>{activeNav}</h1></div><div className="topbar-right"><span className="live-pill"><span className="status-dot"/> LIVE</span><span className="operator">Supervisor / QC</span><div className="avatar">QC</div></div></header><section className="content">{activeNav === 'Production Entry' ? <ProductionEntry session={session} onSaved={() => setRefreshKey(k => k + 1)} /> : activeNav === 'Machine Overview' ? <MachineDashboard refreshKey={refreshKey} /> : <div className="panel placeholder-panel"><h2>{activeNav}</h2><p>This section will use the same saved Supabase production records.</p></div>}</section></main></div>; }
function Root() { const [session,setSession]=useState(null); const [ready,setReady]=useState(false); useEffect(() => { if (!supabase) return setReady(true); supabase.auth.getSession().then(({data}) => { setSession(data.session); setReady(true); }); const {data:listener}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next)); return () => listener.subscription.unsubscribe(); }, []); if (!ready) return <div className="loading">Loading…</div>; return session ? <Dashboard session={session} onLogout={() => supabase.auth.signOut()} /> : <Login onLogin={setSession} />; }
createRoot(document.getElementById('root')).render(<React.StrictMode><Root /></React.StrictMode>);
